### Numpy - Numerical Python
* In python data can come from various sources and can be in various formats it can be image data, text data etc. and is heterogeneous in nature. To make the data readable we have to think it as an array of numbers, an image is an array of numbers with numbers ranging from 0 to 255 .
* Now Python has only 4 basic data types and to think of data as an array we need to store it and manipulate it and that is the reason why <b>Numpy</b> came into Picture.

In [22]:
# To use numpy we have to import it from our anaconda stack where we will get it pre installed
import numpy as np

In [23]:
np.__version__

'1.18.5'

In [24]:
# Creating one dimensional numpy Arrays from list
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

#### Numpy arrays are homogeneous 

In [25]:
# Remeber Python list are heterogeneous but numpy arrays are homogeneous and the data type is same and if it is not same then 
# numpy will upcast them to same data type
a2 = np.array([1,2,3,4,5.])
a2

array([1., 2., 3., 4., 5.])

In [26]:
# Or we can predefine the data type
a3 = np.array([10,15,20,35,40,60.0],dtype = "float32")
a3

array([10., 15., 20., 35., 40., 60.], dtype=float32)

In [27]:
# Numpy arrays are N-Dimensional arrays here n = 1 i.e. One dimensional 
type(a3)

numpy.ndarray

#### Creating Arrays 

In [28]:
# we can create numpy arrays filled with zeroes
np.zeros(10,dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# we can create 2-D arrays all filled with ones
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# we can create 3-D arrays filled with some values
np.full((3,4,5),21)

array([[[21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21]],

       [[21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21]],

       [[21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21],
        [21, 21, 21, 21, 21]]])

In [31]:
# we can create an array with equally spaced values between given range and it will go from 0 to n-1 and we can give step size 
# in decimals too.
np.arange(0,40,1.2)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8, 12. ,
       13.2, 14.4, 15.6, 16.8, 18. , 19.2, 20.4, 21.6, 22.8, 24. , 25.2,
       26.4, 27.6, 28.8, 30. , 31.2, 32.4, 33.6, 34.8, 36. , 37.2, 38.4,
       39.6])

In [32]:
# Linspace will go from 0 to n and will create equally spaced number between start and end and number can be anything whether we
# want 100 numbers the spacing between them would be same
np.linspace(0,40,40)

array([ 0.        ,  1.02564103,  2.05128205,  3.07692308,  4.1025641 ,
        5.12820513,  6.15384615,  7.17948718,  8.20512821,  9.23076923,
       10.25641026, 11.28205128, 12.30769231, 13.33333333, 14.35897436,
       15.38461538, 16.41025641, 17.43589744, 18.46153846, 19.48717949,
       20.51282051, 21.53846154, 22.56410256, 23.58974359, 24.61538462,
       25.64102564, 26.66666667, 27.69230769, 28.71794872, 29.74358974,
       30.76923077, 31.79487179, 32.82051282, 33.84615385, 34.87179487,
       35.8974359 , 36.92307692, 37.94871795, 38.97435897, 40.        ])

In [33]:
# Will generate random numbers between 0 and 1
np.random.random((2,3))

array([[0.8961972 , 0.79654849, 0.13953353],
       [0.65423939, 0.47425814, 0.80704669]])

In [157]:
# will generate random numbers between the given range
a4 = np.random.randint(0,10,(3,3))
a4

array([[0, 5, 5],
       [8, 4, 3],
       [2, 0, 6]])

In [158]:
# we can also create an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Attribute of Arrays 

In [35]:
# to get the shape of array
a4.shape

(3, 3)

In [36]:
# to get the number of dimensions
a4.ndim

2

In [37]:
# size ,i.e. number of elements
a4.size

9

In [112]:
# to get the data type , further we can provide th
a4.dtype

dtype('int32')

#### Elements Access

In [39]:
# we can access elements using square brackets[r,c] ,like we did in python
a1[2]

3

In [40]:
# for multidimensional we can access the element by a comma separated indice.
a4[2,1]

4

In [41]:
# we can update the values too by the same square brackets
a4[2,2] = 9

In [70]:
a4

array([[7, 3, 8],
       [3, 4, 8],
       [0, 4, 9]])

#### Slicing 

In [71]:
a5 = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [103]:
# to get the value from first axis
# here as we can see that we can get the value 3 i.e, from row 0 get the third element
a5[0,2]

3

In [109]:
# here we can see that x-axis = 0 and we are gettin elements from colun 4th i.e, index = 3
a5[:,3]

array([ 4,  8, 12])

In [77]:
# for 2 rows and 3 columns
a5[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [95]:
# two get all rows and every other column
a5[:3,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [98]:
# reversed array
a5[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

#### Aggregations & other Mathematic functions

In [114]:
# we can do aggregation on the values in array
np.sum(a5)

78

In [115]:
np.min(a5)

1

In [116]:
np.max(a5)

12

In [117]:
# for multidimensional aggregation we can use axis
# axis = 0 is used to sum along the columns
np.sum(a5,axis=0)

array([15, 18, 21, 24])

In [119]:
# for row wise aggregation we can use axis = 1
np.sum(a5,axis = 1)

array([10, 26, 42])

In [159]:
np.mean(a5)

6.5

In [160]:
a5 + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [162]:
a5-2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [164]:
a5*8

array([[ 8, 16, 24, 32],
       [40, 48, 56, 64],
       [72, 80, 88, 96]])

In [166]:
a5/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

#### Broadcasting 

In [123]:
# Broadcasting means that we don't need any for loops we can do any operations on arrays
a = np.array([1,9,5])
b = np.array([2,5,90])

In [124]:
a+b

array([ 3, 14, 95])

In [131]:
# we can add numbers to arrays
c = a+100
c

array([101, 109, 105])

In [130]:
# we can check conditions on the numpy array
c[c>105]

array([109])

In [190]:
Arr = np.random.randint(50, 500, size = (4, 6))

In [191]:
Arr

array([[306, 292, 364, 341, 278, 281],
       [ 57, 455, 148, 402, 129, 359],
       [158, 157, 255, 173, 468,  82],
       [103, 410, 167, 108, 392, 173]])

In [197]:
# logical Condition checking
Arr[(Arr>=350) & (Arr<=400)]

array([364, 359, 392])

#### Functions related to shape 

In [149]:
d = np.array([1,3,5,12,6,7,8,9,6,4,4,14])

In [153]:
# o we can reshape the elements as per no . of elements like 12 = 2*6,3*4,4*3
d.reshape(2,6)

array([[ 1,  3,  5, 12,  6,  7],
       [ 8,  9,  6,  4,  4, 14]])

In [154]:
d.reshape(3,4)

array([[ 1,  3,  5, 12],
       [ 6,  7,  8,  9],
       [ 6,  4,  4, 14]])

In [156]:
# we cn transpose them and change there dimensions rows = columns and vice-versa
d.reshape(3,4).T

array([[ 1,  6,  6],
       [ 3,  7,  4],
       [ 5,  8,  4],
       [12,  9, 14]])

#### Combining Data 

In [179]:
J = np.random.randint( 10, size = (6,9))
K = np.random.randint( 100, size = (6,2))
L = np.random.randint( 800, size = (4,9))

In [180]:
J

array([[9, 7, 4, 1, 1, 7, 0, 2, 7],
       [1, 8, 4, 5, 4, 5, 2, 3, 5],
       [7, 6, 9, 6, 2, 0, 8, 1, 9],
       [5, 3, 6, 3, 3, 7, 4, 2, 3],
       [6, 7, 5, 5, 7, 7, 5, 9, 9],
       [9, 9, 7, 1, 7, 5, 4, 6, 8]])

In [173]:
K

array([[77, 97],
       [91, 95],
       [79, 60],
       [ 9,  5],
       [15, 31],
       [12, 46]])

In [181]:
L

array([[490, 447,   4, 735, 315, 601, 540,  10, 203],
       [723, 358,  12, 634,  56, 235, 124, 778, 355],
       [705, 727, 283, 743, 368, 459, 600,  96, 172],
       [673, 277, 758, 297, 793, 370, 697, 453, 270]])

In [182]:
# Horizontal Combining for that the horizontal dimesnions should be same
np.hstack([J,K])

array([[ 9,  7,  4,  1,  1,  7,  0,  2,  7, 99, 52],
       [ 1,  8,  4,  5,  4,  5,  2,  3,  5, 19, 67],
       [ 7,  6,  9,  6,  2,  0,  8,  1,  9, 28, 49],
       [ 5,  3,  6,  3,  3,  7,  4,  2,  3, 56, 59],
       [ 6,  7,  5,  5,  7,  7,  5,  9,  9,  5, 34],
       [ 9,  9,  7,  1,  7,  5,  4,  6,  8, 69, 18]])

In [184]:
# Vertical appending for that the vertical dimesnions should be same
np.vstack([J,L])

array([[  9,   7,   4,   1,   1,   7,   0,   2,   7],
       [  1,   8,   4,   5,   4,   5,   2,   3,   5],
       [  7,   6,   9,   6,   2,   0,   8,   1,   9],
       [  5,   3,   6,   3,   3,   7,   4,   2,   3],
       [  6,   7,   5,   5,   7,   7,   5,   9,   9],
       [  9,   9,   7,   1,   7,   5,   4,   6,   8],
       [490, 447,   4, 735, 315, 601, 540,  10, 203],
       [723, 358,  12, 634,  56, 235, 124, 778, 355],
       [705, 727, 283, 743, 368, 459, 600,  96, 172],
       [673, 277, 758, 297, 793, 370, 697, 453, 270]])